global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'photoshare-api'
    metrics_path: /api/metrics
    static_configs:
      - targets: ['host.docker.internal:3000']
    scrape_interval: 5s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']
